apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-configmap
data:
  initdb.sh: |-
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER skynux_user WITH PASSWORD 'skynux';
      CREATE DATABASE skynux_db;
      GRANT ALL PRIVILEGES ON DATABASE skynux_db TO skynux_user;
    EOSQL