kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany #muchos pods pueden escribir aqui
  hostPath:
    path: "/mnt/data/" #ruta del  cluster en minikube donde se va a guaradar