apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: c2t5bnV4X2Ri
  POSTGRES_USER: c2t5bnV4X3VzZXI=
  POSTGRES_PASSWORD: c2t5bnV4