apiVersion: v1
kind: Secret #Archivo que guarda informacion sensible
metadata:
  name: pgadmin-secret #Nombre del pod
  labels:
    app: postgres #solo es una etiqueta para poder generar busquedas
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: c2FyYXlhckBza3ludXguY2w=
  PGADMIN_DEFAULT_PASSWORD: c2t5bnV4
  PGADMIN_PORT: ODA=